# Logging configuration for Ringer 
version: 1
disable_existing_loggers: False
handlers:
    logfile:
        class: logging.handlers.RotatingFileHandler
        filename: ringer-debug.log
        formatter: simple
        level: INFO
        maxBytes: 104857600
        backupCount: 3
    console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: simple
        level: INFO

formatters:
    simple:
        format: '%(asctime)s %(process)d %(name)s %(funcName)s %(levelname)s %(message)s'
root:
    level: INFO
    handlers: [console, logfile]
    propagate: no
loggers:
    uvicorn:
        level: INFO
        handlers: [console, logfile]
        propagate: no
    fastapi:
        level: INFO
        handlers: [console, logfile]
        propagate: no
    main:
        level: INFO
        handlers: [console, logfile]
        propagate: no

